services:
  frontend:
    image: hoppscotch/hoppscotch-frontend:latest
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    env_file:
      - path: ./default.env
        required: true
    ports:
      - "3000:3000"

  backend:
    image: hoppscotch/hoppscotch-backend:latest
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    env_file:
      - path: ./default.env
        required: true
    # command: "pnpx prisma migrate deploy"
    ports:
      - "3170:3170"

  admin:
    image: hoppscotch/hoppscotch-admin:latest
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    env_file:
      - path: ./default.env
        required: true
    ports:
      - "3100:3100"
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/hosts:/etc/hosts
    depends_on:
      - frontend
      - backend
      - admin
    networks:
      app_net:
        ipv4_address: 172.16.238.14
    ports:
      - 80:80

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  db-data: {}
